FROM node:11.1.0-alpine as build-step
RUN mkdir -p /usr/local/frontend
ENV PATH /usr/local/frontend/node_modules/.bin:$PATH
COPY package.json /usr/local/frontend
COPY package-lock.json /usr/local/frontend
WORKDIR /usr/local/frontend
RUN npm install
RUN npm install react-scripts@3.4.1 -g
COPY . /usr/local/frontend
RUN npm run build

FROM nginx:stable-alpine
COPY --from=build-step /usr/local/frontend/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
