version: "3"
services:
  frontend:
    container_name: frontend
    restart: always
    build: ./frontend
    image: chaintope99/ordermgt_frontend
    ports:
      - "3000:8001"
  orders:
    container_name: orders
    restart: always
    build: ./orders
    image: chaintope99/ordermgt_orders
    ports:
      - "4040:8002"
    links:
      - mongo
  payments:
    container_name: payments
    restart: always
    build: ./payments
    image: chaintope99/ordermgt_payments
    ports:
      - "4040:8003"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27018:27017"
