version: "3"
services:
  frontend:
    container_name: ordermgt_frontend
    image: chaintope99/ordermgt_frontend:latest
    working_dir: /usr/local/frontend
    ports:
      - "8001:3000"
    stdin_open: true    
  orders:
    container_name: ordermgt_orders
    restart: always
    image: chaintope99/ordermgt_orders:latest
    ports:
      - "8002:4044"
    links:
      - mongo
  payments:
    container_name: ordermgt_payments
    image: chaintope99/ordermgt_payments:latest
    ports:
      - "8003:4045"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27018:27017"
