apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "ordermgt.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "ordermgt.name" . }}
    spec:
      containers:
        {{- if .Values.frontend.enabled }}
        - name: {{ include "ordermgt_frontend.fullname" . }}
          image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
          imagePullPolicy:  {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: 80
        {{- end }}
        {{- if .Values.orders.enabled }}
        - name: {{ include "ordermgt_orders.fullname" . }}
          image: {{ .Values.orders.image.repository }}:{{ .Values.orders.image.tag }}
          imagePullPolicy:  {{ .Values.orders.image.pullPolicy }}
          ports:
            - containerPort: 4044
        {{- end }}
