{{- if .Values.frontend.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ordermgt_frontend.fullname" . }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    # Inside the cluster, what port does the service expose?
    - port: {{ .Values.frontend.service.port }}
    # Which port do pods selected by this service expose?
      targetPort:
      protocol: TCP
    # Which port on the node is the service available through?
      nodePort: {{ .Values.frontend.service.nodePort }}
  selector:
    app: {{ include "ordermgt.name" . }}
{{- end }}
